baseURL = "https://github.com/sentreepay/jimmy.gitio.io/"
title = "我的網站"
theme = "PaperMod"

defaultContentLanguage = "zh-tw"
languageCode = "zh-tw"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  # 顯示設定
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # 首頁設定
  profileMode = false
  
  # SEO 設定
  env = "production"
  description = "這是我的個人網站"
  keywords = ["Blog", "Portfolio", "PaperMod"]

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分類"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "標籤"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "歸檔"
    url = "/archives/"
    weight = 30
