baseURL: "https://sentreepay.github.io/jimmy.gitio.io/"
title: "Jimmy的個人網站"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  title: "Jimmy的個人網站"
  description: "歡迎來到我的個人網站"
  keywords: [部落格, 作品集, PaperMod]
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true 
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: "你好!我是Jimmy"
    subtitle: "我是一名熱衷於學習和成長的學生"
    imageUrl: "/images/profile.jpg"
    buttons:
      - name: 教育背景
        url: "/education/"
      - name: 專業技能
        url: "/skills/"

menu:
  main:
    - identifier: education
      name: 教育背景
      url: /education/
      weight: 10
    - identifier: skills
      name: 專業技能 
      url: /skills/
      weight: 20

languages:
  zh-tw:
    languageName: "Chinese"
    weight: 1
